name: grant-tag
run-name: grant-tag
on:
  push:
    branches:
      - master
    paths:
      - Cargo.toml
env:
  CARGO_TERM_COLOR: always
jobs:
  grant-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: detect-serde_structuredqs-version
        with:
          create-tag: false
          version-command: cargo read-manifest --manifest-path=Cargo.toml | jq -r .version
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{steps.detect-serde_structuredqs-version.outputs.current-version}}
          tag_prefix: "serde_structuredqs_v"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
