name: publish-crate
run-name: publish-crate

on:
  push:
    tags:
      - "serde_structuredqs_v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATE_API_TOKEN }}
